### PR TITLE
FIX: travis

### PR DESCRIPTION
**Pull request by massich**

### CODE REVIEW

**Comment by massich** [comment]
@larsoner I don't understand why travis dies there. do you?

**Comment by larsoner** [comment]
Not sure, I'm using a copy-paste-trimmed version in https://github.com/mne-tools/mne-realtime/pull/4, let's see if it does any better

**Comment by massich** [comment]
This was the same. Taken the `.travis.yml` form mne-python and removed almost everything.

**Comment by larsoner** [comment]
The same method, was the result the same? If you do a `diff` between the two versions, are the identical? Hopefully they are not, and somewhere in the different lines you can see what fixed it

**Comment by massich** [comment]
I did the diff. A priory the lines of this are a subset of those in #4, whatever was in the logic branch of the OSX.

Anyways no need to keep looking

**Pull request closed without merging**
