### PR TITLE
Migrate mne realtime

### PR DESCRIPTION
**Pull request by massich**
move `mne.realtime`

Todo:
- [x] migrate the code, adapt it and make it green locally (without fieldtrip)
- [ ] fix the env and CI scripts to make CIs green 
- [ ] add fieldtrip

### CODE REVIEW

**Comment by larsoner** [comment]
Rather than starting from something simple and iterating until the CIs work, why not start with a config that worked (the one from MNE-Python) and whittle it down / remove things that are unnecessary? Otherwise you risk re-living all the (many!) difficult experiences that led to MNE-Python CIs being configured the way that they are.

**Comment by massich** [comment]
that's the approach I'm taking now with circle. The template works if you don't do something too much MNE. (I've used it in several projects and it seemed to work) Not here. Which means I'll have to update `mne-tools/mne-project-template`

**Comment by massich** [comment]
@larsoner can you activate azure for me? thx

**Comment by larsoner** [comment]
Should be done/working: https://dev.azure.com/mne-tools/mne-realtime/_build?definitionId=2&_a=summary

**Comment by larsoner** [comment]
@massich I'll push some commits to see if I can get things green. It would be good to get this done ASAP so we can link to it from the mne-python doc.

**Pull request closed without merging**
