### PR TITLE
DOC: Remove psd_welch usage and replace with Spectrum

### PR DESCRIPTION
**Pull request by rob-luke**
I noticed in #44 that this usage of psd_welch was causing the documentation build to fail, so have updated it to use the newer spectrum object.

### CODE REVIEW

**Comment by rob-luke** [comment]
The docs now build on CircleCI but other warning are causing the tick to go ❌
See built doc here: https://output.circle-artifacts.com/output/job/a2de39c5-c644-4da1-9098-a86d7fd1c6f3/artifacts/0/dev/auto_examples/plot_ftclient_rt_compute_psd.html#sphx-glr-auto-examples-plot-ftclient-rt-compute-psd-py

Could we take a baby step here @larsoner @agramfort and merge this fix and then iterate?

**Comment by rob-luke** [comment]
Actually, a larger issue, I see that the pytest workflow has been disabled. @agramfort @larsoner @drammock could someone please enable it here: https://github.com/mne-tools/mne-realtime/actions/workflows/linux.yml thanks

**Comment by agramfort** [comment]
done

**Comment by rob-luke** [comment]
Thanks @larsoner. And thanks for sneaking those other fixes in too, that's much quicker than me stringing PRs over a week 🚀

**Pull request merged**
